var html="<h3> 自宅で謎解きが出来る書籍紹介<\/h3>";
		    
    /* 紹介本用 */
var result = new Array();

var count = 38;
var roop = 2;
var checkArray = new Array();
var number_array = new Array();

for(var i=0; i<roop; i++){
	
	//指定範囲内の数値を整数として取得
	var rondomNum = Math.floor(Math.random()*count);

	var checkArray = number_array.indexOf(rondomNum);
		
	if(checkArray == -1){
		//number_array配列になければ、number_arrayに入れる。
		number_array.push(rondomNum);
	}else{
	         //number_array配列にある場合は、roopを加算する。
		roop++;
	}
}


var num="";
for (num of number_array) {
	if (num == 0) {
	    	html +=  "<h4>リアル脱出ゲームの公式過去問題集<\/h4>";
	    	html += '<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4905158133/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/41rhQs%2BcwPL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4905158133/lirlia-22/ref=nosim/" target="_blank" >リアル脱出ゲーム 公式過去問題集</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">SCRAP スモール出版 2013-09-27    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%AA%E3%82%A2%E3%83%AB%E8%84%B1%E5%87%BA%E3%82%B2%E3%83%BC%E3%83%A0%E3%80%80%E5%85%AC%E5%BC%8F%E9%81%8E%E5%8E%BB%E5%95%8F%E9%A1%8C%E9%9B%86&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}

	if (num == 1) {
	//10人
	    	html += "<h4>一番面白いSCRAPの脱出ゲームブック<\/h4>";
	    	html += '<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845622963/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51uS1hSIb0L._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845622963/lirlia-22/ref=nosim/" target="_blank" >十人の憂鬱な容疑者 素敵なパーティ、死体がふたつ (脱出ゲームブック)</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">SCRAP リットーミュージック 2013-09-25    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E5%8D%81%E4%BA%BA%E3%81%AE%E6%86%82%E9%AC%B1%E3%81%AA%E5%AE%B9%E7%96%91%E8%80%85%20%E7%B4%A0%E6%95%B5%E3%81%AA%E3%83%91%E3%83%BC%E3%83%86%E3%82%A3%E3%80%81%E6%AD%BB%E4%BD%93%E3%81%8C%E3%81%B5%E3%81%9F%E3%81%A4&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	
	//スパイ
	if (num == 2) {
	    	html += "<h4>最近発売のSCRAPの脱出ゲームブック<\/h4>";
	    	html += '<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845625725/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/511SgH1QPJL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845625725/lirlia-22/ref=nosim/" target="_blank" >聡明なスパイは耳がいい 謎はメロディーの中にある (CDほか付) (脱出ゲームブック)</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">SCRAP リットーミュージック 2015-03-20    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E8%81%A1%E6%98%8E%E3%81%AA%E3%82%B9%E3%83%91%E3%82%A4%E3%81%AF%E8%80%B3%E3%81%8C%E3%81%84%E3%81%84%20%E8%AC%8E%E3%81%AF%E3%83%A1%E3%83%AD%E3%83%87%E3%82%A3%E3%83%BC%E3%81%AE%E4%B8%AD%E3%81%AB%E3%81%82%E3%82%8B&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
    	}

	//キソニー
	if (num == 3) {
	    	html += "<h4>謎解きで英語を勉強！<\/h4>";
	    	html += '<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4140351373/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/61Wyjw7r9jL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4140351373/lirlia-22/ref=nosim/" target="_blank" >英語で謎解き! 楽しい英単語―キソニーとまぼろしの砂時計</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">竹吉 俊輔 NHK出版 2015-12-09    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E8%8B%B1%E8%AA%9E%E3%81%A7%E8%AC%8E%E8%A7%A3%E3%81%8D%21%20%E6%A5%BD%E3%81%97%E3%81%84%E8%8B%B1%E5%8D%98%E8%AA%9E%E2%80%95%E3%82%AD%E3%82%BD%E3%83%8B%E3%83%BC%E3%81%A8%E3%81%BE%E3%81%BC%E3%82%8D%E3%81%97%E3%81%AE%E7%A0%82%E6%99%82%E8%A8%88&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//人狼村
	if (num == 4) {
		html +="<h4>人狼×脱出ゲームブック<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845620715/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51cosQ0LSJL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845620715/lirlia-22/ref=nosim/" target="_blank" >人狼村からの脱出 狼を見つけないと、殺される (脱出ゲームブック)</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">SCRAP リットーミュージック 2012-05-25    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E4%BA%BA%E7%8B%BC%E6%9D%91%E3%81%8B%E3%82%89%E3%81%AE%E8%84%B1%E5%87%BA%20%E7%8B%BC%E3%82%92%E8%A6%8B%E3%81%A4%E3%81%91%E3%81%AA%E3%81%84%E3%81%A8%E3%80%81%E6%AE%BA%E3%81%95%E3%82%8C%E3%82%8B&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}

	//ふたご島
	if (num == 5) {
		html +="<h4>2冊同時？のゲームブック<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845621967/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51E2m4uziqL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845621967/lirlia-22/ref=nosim/" target="_blank" >ふたご島からの脱出 少年は戻りたいと思った。少女は救いたいと願った。 (脱出ゲームブック)</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">SCRAP リットーミュージック 2013-02-25    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%81%B5%E3%81%9F%E3%81%94%E5%B3%B6%E3%81%8B%E3%82%89%E3%81%AE%E8%84%B1%E5%87%BA%20%E5%B0%91%E5%B9%B4%E3%81%AF%E6%88%BB%E3%82%8A%E3%81%9F%E3%81%84%E3%81%A8%E6%80%9D%E3%81%A3%E3%81%9F%E3%80%82%E5%B0%91%E5%A5%B3%E3%81%AF%E6%95%91%E3%81%84%E3%81%9F%E3%81%84%E3%81%A8%E9%A1%98%E3%81%A3%E3%81%9F%E3%80%82%20%28%E8%84%B1%E5%87%BA%E3%82%B2%E3%83%BC%E3%83%A0%E3%83%96%E3%83%83%E3%82%AF%29&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	
	}
	//人狼村DVD
	if (num == 6) {
		html +="<h4>人狼村がDVDに！<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B00FZ2VQ38/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51pRblaYzEL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B00FZ2VQ38/lirlia-22/ref=nosim/" target="_blank" >リアル脱出ゲームDVD 『人狼村からの脱出』</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">ゲーム ビーイング 2013-12-13    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%AA%E3%82%A2%E3%83%AB%E8%84%B1%E5%87%BA%E3%82%B2%E3%83%BC%E3%83%A0DVD%20%E3%80%8E%E4%BA%BA%E7%8B%BC%E6%9D%91%E3%81%8B%E3%82%89%E3%81%AE%E8%84%B1%E5%87%BA%E3%80%8F&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//デスノ
	if (num == 7) {
		html +="<h4>DeathNote×パズル<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4087807207/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51yO2QlMIRL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4087807207/lirlia-22/ref=nosim/" target="_blank" >DEATH NOTE × SCRAP 死と砂の世界からの脱出</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">(株)SCRAP,日下部 匡俊 集英社 2014-05-30    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=DEATH%20NOTE%20%C3%97%20SCRAP%20%E6%AD%BB%E3%81%A8%E7%A0%82%E3%81%AE%E4%B8%96%E7%95%8C%E3%81%8B%E3%82%89%E3%81%AE%E8%84%B1%E5%87%BA&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//幽霊船
	if (num == 8) {
		html +="<h4>大人の謎解き絵本<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845624273/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51KH4cTkOaL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845624273/lirlia-22/ref=nosim/" target="_blank" >幽霊城からの脱出 (大人の謎解き絵本)</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">SCRAP リットーミュージック 2014-06-20    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E5%B9%BD%E9%9C%8A%E5%9F%8E%E3%81%8B%E3%82%89%E3%81%AE%E8%84%B1%E5%87%BA%20%28%E5%A4%A7%E4%BA%BA%E3%81%AE%E8%AC%8E%E8%A7%A3%E3%81%8D%E7%B5%B5%E6%9C%AC%29&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//パズルノート　学園の謎を解き明かせ
	if (num == 9) {
		html +="<h4>定番のパズルを！<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4890727906/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51OuIHZmuML._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4890727906/lirlia-22/ref=nosim/" target="_blank" >パズルノート 学園の謎を解き明かせ</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">ニコリ ニコリ 2012-02-10    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%91%E3%82%BA%E3%83%AB%E3%83%8E%E3%83%BC%E3%83%88%20%E5%AD%A6%E5%9C%92%E3%81%AE%E8%AC%8E%E3%82%92%E8%A7%A3%E3%81%8D%E6%98%8E%E3%81%8B%E3%81%9B&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//6人
	if (num == 10) {
		html +="<h4>本とスマホを持って東京を探索！<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845624389/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51g2J-2nGmL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845624389/lirlia-22/ref=nosim/" target="_blank" >東京謎解きツアーブック 消えた6人の謎 (NAZO-BOOKS)</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">HAT-CRi,よだかのレコード リットーミュージック 2014-07-30    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E6%9D%B1%E4%BA%AC%E8%AC%8E%E8%A7%A3%E3%81%8D%E3%83%84%E3%82%A2%E3%83%BC%E3%83%96%E3%83%83%E3%82%AF%20%E6%B6%88%E3%81%88%E3%81%9F6%E4%BA%BA%E3%81%AE%E8%AC%8E%20%28NAZO-BOOKS%29&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//初恋
	if (num == 11) {
		html +="<h4>謎解き初心者はこれを是非！<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4905158206/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51AkrXvNjUL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4905158206/lirlia-22/ref=nosim/" target="_blank" >謎解きアドベンチャーBOOK 木ノ下くんの初恋</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">ろじっくぱらだいすワタナベ スモール出版 2014-07-17    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E8%AC%8E%E8%A7%A3%E3%81%8D%E3%82%A2%E3%83%89%E3%83%99%E3%83%B3%E3%83%81%E3%83%A3%E3%83%BCBOOK%20%E6%9C%A8%E3%83%8E%E4%B8%8B%E3%81%8F%E3%82%93%E3%81%AE%E5%88%9D%E6%81%8B&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//廃校
	if (num == 12) {
		html +="<h4>ホラー×リアル脱出ゲームDVD<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B00AF2KL1G/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51On89wBFLL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B00AF2KL1G/lirlia-22/ref=nosim/" target="_blank" >PROJECT DABA×リアル脱出ゲーム 呪われた廃校からの脱出 -成仏させないと、ここから出られない- [DVD]</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">DABA マリン・エンタテインメント 2013-02-27    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=PROJECT%20DABA%C3%97%E3%83%AA%E3%82%A2%E3%83%AB%E8%84%B1%E5%87%BA%E3%82%B2%E3%83%BC%E3%83%A0%20%E5%91%AA%E3%82%8F%E3%82%8C%E3%81%9F%E5%BB%83%E6%A0%A1%E3%81%8B%E3%82%89%E3%81%AE%E8%84%B1%E5%87%BA%20-%E6%88%90%E4%BB%8F%E3%81%95%E3%81%9B%E3%81%AA%E3%81%84%E3%81%A8%E3%80%81%E3%81%93%E3%81%93%E3%81%8B%E3%82%89%E5%87%BA%E3%82%89%E3%82%8C%E3%81%AA%E3%81%84-%20%5BDVD%5D&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//マーマレード
	if (num == 13) {
		html +="<h4>謎を解くために生まれた女、マダム・マーマレード<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4062186187/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51Lfpd9GPhL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4062186187/lirlia-22/ref=nosim/" target="_blank" >マダム・マーマレードと暗い日曜日</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">堀田 延 講談社 2013-09-27    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%9E%E3%83%80%E3%83%A0%E3%83%BB%E3%83%9E%E3%83%BC%E3%83%9E%E3%83%AC%E3%83%BC%E3%83%89%E3%81%A8%E6%9A%97%E3%81%84%E6%97%A5%E6%9B%9C%E6%97%A5&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//勇者と魔神
	if (num == 14) {
		html +="<h4>東京ボウズの謎解きブック！<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4905158230/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/61iZPVRcCwL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4905158230/lirlia-22/ref=nosim/" target="_blank" >謎解きアドベンチャーBOOK 勇者と魔神 〜武器と防具は文房具〜</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">東京ボウズ スモール出版 2014-11-13    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E8%AC%8E%E8%A7%A3%E3%81%8D%E3%82%A2%E3%83%89%E3%83%99%E3%83%B3%E3%83%81%E3%83%A3%E3%83%BCBOOK%20%E5%8B%87%E8%80%85%E3%81%A8%E9%AD%94%E7%A5%9E%20%E3%80%9C%E6%AD%A6%E5%99%A8%E3%81%A8%E9%98%B2%E5%85%B7%E3%81%AF%E6%96%87%E6%88%BF%E5%85%B7%E3%80%9C&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//あなたクエスト
	if (num == 15) {
		html +="<h4>謎を解いて物語を紡ぐあなたクエスト<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845624370/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/41CoYg9VtkL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845624370/lirlia-22/ref=nosim/" target="_blank" >あなたクエスト 世界とあなたを結ぶゲームブック (NAZO-BOOKS)</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">千石 一郎 リットーミュージック 2014-09-05    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%81%82%E3%81%AA%E3%81%9F%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%88%20%E4%B8%96%E7%95%8C%E3%81%A8%E3%81%82%E3%81%AA%E3%81%9F%E3%82%92%E7%B5%90%E3%81%B6%E3%82%B2%E3%83%BC%E3%83%A0%E3%83%96%E3%83%83%E3%82%AF%20%28NAZO-BOOKS%29&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//密室美少女
	if (num == 16) {
		html +="<h4>リアル脱出ゲーム初めてのドラマ化！<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B00G534LAG/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/513tf-Y%2BhuL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B00G534LAG/lirlia-22/ref=nosim/" target="_blank" >リアル脱出ゲーム 密室美少女 [DVD]</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">荒井萌 ポニーキャニオン 2013-12-27    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%AA%E3%82%A2%E3%83%AB%E8%84%B1%E5%87%BA%E3%82%B2%E3%83%BC%E3%83%A0%20%E5%AF%86%E5%AE%A4%E7%BE%8E%E5%B0%91%E5%A5%B3%20%5BDVD%5D&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//千年クイズ
	if (num == 17) {
		html +="<h4>昭和の名作謎解集！<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845625008/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51j5gui05KL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4845625008/lirlia-22/ref=nosim/" target="_blank" >千年クイズ 日本人の脳を活性化してきた平安〜昭和の名作謎解き集 (NAZO-BOOKS)</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">清水 文子 リットーミュージック 2014-09-25    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E5%8D%83%E5%B9%B4%E3%82%AF%E3%82%A4%E3%82%BA%20%E6%97%A5%E6%9C%AC%E4%BA%BA%E3%81%AE%E8%84%B3%E3%82%92%E6%B4%BB%E6%80%A7%E5%8C%96%E3%81%97%E3%81%A6%E3%81%8D%E3%81%9F%E5%B9%B3%E5%AE%89%E3%80%9C%E6%98%AD%E5%92%8C%E3%81%AE%E5%90%8D%E4%BD%9C%E8%AC%8E%E8%A7%A3%E3%81%8D%E9%9B%86%20%28NAZO-BOOKS%29&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//鷹の爪団
	if (num == 18) {
		html +="<h4>鷹の爪団が謎解きに！<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B00RFNKNAC/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51L2fVR8B8L._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B00RFNKNAC/lirlia-22/ref=nosim/" target="_blank" >謎解きゲームDVD 秘密結社鷹の爪「人形屋敷の魔人」</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">ゲーム ビーイング 2015-02-27    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E8%AC%8E%E8%A7%A3%E3%81%8D%E3%82%B2%E3%83%BC%E3%83%A0DVD%20%E7%A7%98%E5%AF%86%E7%B5%90%E7%A4%BE%E9%B7%B9%E3%81%AE%E7%88%AA%E3%80%8C%E4%BA%BA%E5%BD%A2%E5%B1%8B%E6%95%B7%E3%81%AE%E9%AD%94%E4%BA%BA%E3%80%8D&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//怪盗ジョーカー
	if (num == 19) {
		html +="<h4>怪盗ジョーカー　リアル予告状ゲーム<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B00P0GATVE/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/61JT27D%2ByKL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B00P0GATVE/lirlia-22/ref=nosim/" target="_blank" >怪盗ジョーカー リアル予告状ゲーム ~豪華特急の秘密篇~</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;"> バンダイ 2014-12-27    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E6%80%AA%E7%9B%97%E3%82%B8%E3%83%A7%E3%83%BC%E3%82%AB%E3%83%BC%20%E3%83%AA%E3%82%A2%E3%83%AB%E4%BA%88%E5%91%8A%E7%8A%B6%E3%82%B2%E3%83%BC%E3%83%A0%20~%E8%B1%AA%E8%8F%AF%E7%89%B9%E6%80%A5%E3%81%AE%E7%A7%98%E5%AF%86%E7%AF%87~&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//クィアウルフ
	if (num == 20) {
		html +="<h4>パズル対策の決定版！<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4905158257/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51bA9I4ekvL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4905158257/lirlia-22/ref=nosim/" target="_blank" >謎解きパズルドリル</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">Xevs スモール出版 2015-04-10    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E8%AC%8E%E8%A7%A3%E3%81%8D%E3%83%91%E3%82%BA%E3%83%AB%E3%83%89%E3%83%AA%E3%83%AB&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//モンハン
	if (num == 21) {
		html +="<h4>モンスターハンター×謎解き！<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4047302570/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/61z5PzwuU1L._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4047302570/lirlia-22/ref=nosim/" target="_blank" >謎解き×ゲーム モンスターハンター謎BOOK</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">ファミ通コンテンツ企画編集部 KADOKAWA/エンターブレイン 2015-02-05    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E8%AC%8E%E8%A7%A3%E3%81%8D%C3%97%E3%82%B2%E3%83%BC%E3%83%A0%20%E3%83%A2%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%8F%E3%83%B3%E3%82%BF%E3%83%BC%E8%AC%8EBOOK&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//右京
	if (num == 22) {
		html +="<h4>謎が解けるようになるためには？<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4833471159/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51EvFm0lppL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4833471159/lirlia-22/ref=nosim/" target="_blank" >ドラマ「相棒」はビジネスの教科書だ！杉下右京に学ぶ「謎解きの発想術」 ―　もし、あなたがこの天才の頭脳をもっていたら？ (プレジデントムック)</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">勝見 明 プレジデント社 2010-10-22    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%89%E3%83%A9%E3%83%9E%E3%80%8C%E7%9B%B8%E6%A3%92%E3%80%8D%E3%81%AF%E3%83%93%E3%82%B8%E3%83%8D%E3%82%B9%E3%81%AE%E6%95%99%E7%A7%91%E6%9B%B8%E3%81%A0%EF%BC%81%E6%9D%89%E4%B8%8B%E5%8F%B3%E4%BA%AC%E3%81%AB%E5%AD%A6%E3%81%B6%E3%80%8C%E8%AC%8E%E8%A7%A3%E3%81%8D%E3%81%AE%E7%99%BA%E6%83%B3%E8%A1%93%E3%80%8D%20%E2%80%95%E3%80%80%E3%82%82%E3%81%97%E3%80%81%E3%81%82%E3%81%AA%E3%81%9F%E3%81%8C%E3%81%93%E3%81%AE%E5%A4%A9%E6%89%8D%E3%81%AE%E9%A0%AD%E8%84%B3%E3%82%92%E3%82%82%E3%81%A3%E3%81%A6%E3%81%84%E3%81%9F%E3%82%89%EF%BC%9F%20%28%E3%83%97%E3%83%AC%E3%82%B8%E3%83%87%E3%83%B3%E3%83%88%E3%83%A0%E3%83%83%E3%82%AF%29&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//1枚クイズ
	if (num == 23) {
		html +="<h4>謎を解きまくろう！<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4054055699/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51gcLdFLQJL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4054055699/lirlia-22/ref=nosim/" target="_blank" >1枚クイズ</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">秋山 慎治 学研教育出版 2012-12    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=1%E6%9E%9A%E3%82%AF%E3%82%A4%E3%82%BA&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	//謎箱
	if (num == 24) {
		html +="<h4>SCRAPの謎箱！謎を解いて箱を開けよう<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B00SBD0Y36/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/416xjscv44L._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B00SBD0Y36/lirlia-22/ref=nosim/" target="_blank" >ワンピース謎箱2 エピソードオブチョッパー</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;"></div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%AF%E3%83%B3%E3%83%94%E3%83%BC%E3%82%B9%E8%AC%8E%E7%AE%B12%20%E3%82%A8%E3%83%94%E3%82%BD%E3%83%BC%E3%83%89%E3%82%AA%E3%83%96%E3%83%81%E3%83%A7%E3%83%83%E3%83%91%E3%83%BC&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}

	//タカラッシュオフィシャル
	if (num == 25) {
		html +="<h4>タカラッシュのオフィシャルブック！<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4594072992/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/61Sjzr5CBOL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4594072992/lirlia-22/ref=nosim/" target="_blank" >タカラッシュ！オフィシャルブック　BOOK版リアル宝探し　謎いっぱいの不思議な本</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">　 扶桑社 2015-07-18    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%82%BF%E3%82%AB%E3%83%A9%E3%83%83%E3%82%B7%E3%83%A5%EF%BC%81%E3%82%AA%E3%83%95%E3%82%A3%E3%82%B7%E3%83%A3%E3%83%AB%E3%83%96%E3%83%83%E3%82%AF%E3%80%80BOOK%E7%89%88%E3%83%AA%E3%82%A2%E3%83%AB%E5%AE%9D%E6%8E%A2%E3%81%97%E3%80%80%E8%AC%8E%E3%81%84%E3%81%A3%E3%81%B1%E3%81%84%E3%81%AE%E4%B8%8D%E6%80%9D%E8%AD%B0%E3%81%AA%E6%9C%AC&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}

	//女神転生
	if (num == 26) {
		html +="<h4>女神転生×謎解きCD<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B0109K5OPQ/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/61BXXdc7QwL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B0109K5OPQ/lirlia-22/ref=nosim/" target="_blank" >ドラマチック謎解きゲームCD 真・女神転生 明ケナイ夜カラノ脱出</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">VARIOUS ARTISTS エグジットチューンズ 2015-09-02    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%89%E3%83%A9%E3%83%9E%E3%83%81%E3%83%83%E3%82%AF%E8%AC%8E%E8%A7%A3%E3%81%8D%E3%82%B2%E3%83%BC%E3%83%A0CD%20%E7%9C%9F%E3%83%BB%E5%A5%B3%E7%A5%9E%E8%BB%A2%E7%94%9F%20%E6%98%8E%E3%82%B1%E3%83%8A%E3%82%A4%E5%A4%9C%E3%82%AB%E3%83%A9%E3%83%8E%E8%84%B1%E5%87%BA&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}

	//リアル恋愛
	if (num == 27) {
		html +="<h4>リアル恋愛脱出ゲーム<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/484562771X/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51GpgYH74YL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/484562771X/lirlia-22/ref=nosim/" target="_blank" >リアル恋愛ゲームブック  片想いからの脱出 「運命の人」と、両想いを目指せ!  (マップ、手紙付)</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">SCRAP リットーミュージック 2016-02-12    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%AA%E3%82%A2%E3%83%AB%E6%81%8B%E6%84%9B%E3%82%B2%E3%83%BC%E3%83%A0%E3%83%96%E3%83%83%E3%82%AF%20%20%E7%89%87%E6%83%B3%E3%81%84%E3%81%8B%E3%82%89%E3%81%AE%E8%84%B1%E5%87%BA%20%E3%80%8C%E9%81%8B%E5%91%BD%E3%81%AE%E4%BA%BA%E3%80%8D%E3%81%A8%E3%80%81%E4%B8%A1%E6%83%B3%E3%81%84%E3%82%92%E7%9B%AE%E6%8C%87%E3%81%9B%21%20%20%28%E3%83%9E%E3%83%83%E3%83%97%E3%80%81%E6%89%8B%E7%B4%99%E4%BB%98%29&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}

	//レイトン教授	
	if (num == 28) {
		html +="<h4>DSで謎解きならレイトン教授<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B004N3BOVO/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51gqGfn1HkL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B004N3BOVO/lirlia-22/ref=nosim/" target="_blank" >レイトン教授と奇跡の仮面</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;"> レベルファイブ 2011-02-26    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%AC%E3%82%A4%E3%83%88%E3%83%B3%E6%95%99%E6%8E%88%E3%81%A8%E5%A5%87%E8%B7%A1%E3%81%AE%E4%BB%AE%E9%9D%A2&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}

	//レイトン教授
	if (num == 29) {
		html +="<h4>DSで謎解きならレイトン教授<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B00AZUYU9M/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/61JH3Xm2kOL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B00AZUYU9M/lirlia-22/ref=nosim/" target="_blank" >レイトン教授と超文明Aの遺産</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;"> レベルファイブ 2013-02-28    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%AC%E3%82%A4%E3%83%88%E3%83%B3%E6%95%99%E6%8E%88%E3%81%A8%E8%B6%85%E6%96%87%E6%98%8EA%E3%81%AE%E9%81%BA%E7%94%A3&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	
	//パズドラ
	if (num == 30) {
		html +="<h4>パズドラ×謎解き！<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/404733071X/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51IKWQlVgsL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/404733071X/lirlia-22/ref=nosim/" target="_blank" >謎解き×ゲーム パズドラ謎BOOK (エンターブレインムック)</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">よだかのレコード KADOKAWA/エンターブレイン 2016-02-26    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E8%AC%8E%E8%A7%A3%E3%81%8D%C3%97%E3%82%B2%E3%83%BC%E3%83%A0%20%E3%83%91%E3%82%BA%E3%83%89%E3%83%A9%E8%AC%8EBOOK%20%28%E3%82%A8%E3%83%B3%E3%82%BF%E3%83%BC%E3%83%96%E3%83%AC%E3%82%A4%E3%83%B3%E3%83%A0%E3%83%83%E3%82%AF%29&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	
	//究極謎
	if (num == 31) {
		html +="<h4>SCRAP公式　謎解き対策<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4990900405/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/319l8DmsjFL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4990900405/lirlia-22/ref=nosim/" target="_blank" >リアル脱出ゲーム presents 究極の謎本</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">SCRAP SCRAP出版 2016-06-30    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%AA%E3%82%A2%E3%83%AB%E8%84%B1%E5%87%BA%E3%82%B2%E3%83%BC%E3%83%A0%20presents%20%E7%A9%B6%E6%A5%B5%E3%81%AE%E8%AC%8E%E6%9C%AC&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}

	//謎解き手帳	
	if (num == 32) {
	  	html +="<h4>毎週謎が解ける手帳2017<\/h4>";
	  	html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/499090043X/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/21malUs0EUL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/499090043X/lirlia-22/ref=nosim/" target="_blank" >謎解き手帳2017</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">SCRAP SCRAP出版 2016-12-22    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E8%AC%8E%E8%A7%A3%E3%81%8D%E6%89%8B%E5%B8%B32017&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}

	//究極クロスワード
 	if (num == 33) {
	  	html +="<h4>SCRAP公式　感動のクロスワード<\/h4>";
	  	html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4990900448/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/41bB5x3%2BGUL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4990900448/lirlia-22/ref=nosim/" target="_blank" >リアル脱出ゲーム presents 究極のクロスワード本</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">SCRAP SCRAP出版 2016-12-30    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%AA%E3%82%A2%E3%83%AB%E8%84%B1%E5%87%BA%E3%82%B2%E3%83%BC%E3%83%A0%20presents%20%E7%A9%B6%E6%A5%B5%E3%81%AE%E3%82%AF%E3%83%AD%E3%82%B9%E3%83%AF%E3%83%BC%E3%83%89%E6%9C%AC&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}

	//ルネ
 	if (num == 34) {
	  	html +="<h4>マルチ主人公の謎解きブック<\/h4>";
	  	html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4990900421/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51Z7nrpC69L._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4990900421/lirlia-22/ref=nosim/" target="_blank" >リアル脱出ゲームブックvol.1 ルネと不思議な箱: その町で少女は過去の夢を見る</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">SCRAP SCRAP出版 2016-10-19    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%AA%E3%82%A2%E3%83%AB%E8%84%B1%E5%87%BA%E3%82%B2%E3%83%BC%E3%83%A0%E3%83%96%E3%83%83%E3%82%AFvol.1%20%E3%83%AB%E3%83%8D%E3%81%A8%E4%B8%8D%E6%80%9D%E8%AD%B0%E3%81%AA%E7%AE%B1%3A%20%E3%81%9D%E3%81%AE%E7%94%BA%E3%81%A7%E5%B0%91%E5%A5%B3%E3%81%AF%E9%81%8E%E5%8E%BB%E3%81%AE%E5%A4%A2%E3%82%92%E8%A6%8B%E3%82%8B&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
	
	//レイトン教授	
	if (num == 35) {
		html +="<h4>DSで謎解きならレイトン教授<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B002WRGKBW/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51os-0-W0FL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B002WRGKBW/lirlia-22/ref=nosim/" target="_blank" >レイトン教授と魔神の笛</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;"> レベルファイブ 2009-11-26    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%AC%E3%82%A4%E3%83%88%E3%83%B3%E6%95%99%E6%8E%88%E3%81%A8%E9%AD%94%E7%A5%9E%E3%81%AE%E7%AC%9B&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}

	//レイトン教授
	if (num == 36) {
		html +="<h4>DSで謎解きならレイトン教授<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B000N3PKEK/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/51UDmpgAMxL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B000N3PKEK/lirlia-22/ref=nosim/" target="_blank" >レイトン教授と不思議な町</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;"> レベルファイブ 2007-02-15    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%AC%E3%82%A4%E3%83%88%E3%83%B3%E6%95%99%E6%8E%88%E3%81%A8%E4%B8%8D%E6%80%9D%E8%AD%B0%E3%81%AA%E7%94%BA&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}

	//逆転裁判xレイトン教授	
	if (num == 37) {
		html +="<h4>レイトン教授VS逆転裁判<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B004GTLUIC/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/61nNmrAvP-L._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/B004GTLUIC/lirlia-22/ref=nosim/" target="_blank" >レイトン教授VS逆転裁判</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;"> レベルファイブ 2012-11-29    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%83%AC%E3%82%A4%E3%83%88%E3%83%B3%E6%95%99%E6%8E%88VS%E9%80%86%E8%BB%A2%E8%A3%81%E5%88%A4&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}

	//アリス
 	if (num == 38) {
	  	html +="<h4>鏡の国のアリスが謎解きに<\/h4>";
		html +='<div class="kaerebalink-box" style="text-align:left;padding-bottom:20px;font-size:small;/zoom: 1;overflow: hidden;"><div class="kaerebalink-image" style="float:left;margin:0 15px 10px 0;"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4766126807/lirlia-22/ref=nosim/" target="_blank" ><img src="https://images-fe.ssl-images-amazon.com/images/I/61W5WIdATgL._SL160_.jpg" style="border: none;" /></a></div><div class="kaerebalink-info" style="line-height:120%;/zoom: 1;overflow: hidden;"><div class="kaerebalink-name" style="margin-bottom:10px;line-height:120%"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4766126807/lirlia-22/ref=nosim/" target="_blank" >アリスとキャロルのパズルランド 不思議の国の謎解きブック</a><div class="kaerebalink-powered-date" style="font-size:8pt;margin-top:5px;font-family:verdana;line-height:120%">posted with <a href="http://kaereba.com" rel="nofollow" target="_blank">カエレバ</a></div></div><div class="kaerebalink-detail" style="margin-bottom:5px;">R.W.ガランド グラフィック社 2014-12-05    </div><div class="kaerebalink-link1" style="margin-top:10px;"><div class="shoplinkamazon" style="display:inline;margin-right:5px"><a href="http://www.amazon.co.jp/gp/search?keywords=%E3%82%A2%E3%83%AA%E3%82%B9%E3%81%A8%E3%82%AD%E3%83%A3%E3%83%AD%E3%83%AB%E3%81%AE%E3%83%91%E3%82%BA%E3%83%AB%E3%83%A9%E3%83%B3%E3%83%89%20%E4%B8%8D%E6%80%9D%E8%AD%B0%E3%81%AE%E5%9B%BD%E3%81%AE%E8%AC%8E%E8%A7%A3%E3%81%8D%E3%83%96%E3%83%83%E3%82%AF&__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&tag=lirlia-22" target="_blank" >Amazonで購入</a></div></div></div><div class="booklink-footer" style="clear: left"></div></div>';
	}
}

result.push(html);
var bookHTML = document.querySelector("div#book");

if(result.length > 0 && bookHTML != null) {
	bookHTML.innerHTML = html;
}
